DEVICE: cuda                # Training device (cuda, cpu, cuda:0, cuda:1)

MODEL:
    MODEL_NAME: GRU
    PRETRAINED: 

DATA:
    DATASET: NORM_FREQ_VAD
    SAMPLE_RATE: 16000          
    SAMPLE_LENGTH: 10
    N_FFT: 512
    FRAME_LENGTH: 512
    HOP_LENGTH: 256
    FFT_WINDOW: HANNING
    ONLINE_AUG: TRUE
    SNR_RANGE: [-5, 30]
    VAD_FREQ_FLOOR: 300
    VAD_FREQ_CEIL: 5000

    CLEAN_DIR:
    NOISE_DIR:
    NOISY_DIR:
    RIR_DIR:

TRAIN:
    EPOCHS: 5                   # number of epochs to train
    BATCH_SIZE: 256             # batch size to use
    EVAL_INTERVAL: 1            # evaluation interval
    AMP: false                  # Mixed Precision Training
    LR: 0.001                 # lr = (batch_size / 1024) * 1e-3
    DECAY: 0.005                # lr decay rate
    LOSSES:
    SAVE_DIR:

TEST:
    TEST_DIR: