DATASETS:
  PREPROCESS: spectrum
  CLEAN_DIR: F:\GitWorkSpace\noise-xorcist\datasets\data\training_set\clean
  NOISY_DIR: F:\GitWorkSpace\noise-xorcist\datasets\data\training_set\noisy
  FORMAT: wav

MODEL:
  BACKBONE:
    NAME: build_nsnet_backbone
    PRETRAIN: false
    INPUT_DIM: 129

  LOSSES:
    NAME: ("WeightedSpeechDistortionLoss",)

    WSD:
      SCALE: 1.
      INDEX: 0
      ALPHA: 0.4
      EPS: 1e-7

INPUT:
  SAMPLE_RATE: 16000
  FRAME_LEN: 128
  HOP_LEN: 128
  NFFT: 256
  WIN_TYPE: hanning
  NORMAL: True
  FEAT_TYPE: ("LogPowerSpectrum",)


DATALOADER:
  NUM_WORKERS: 4


SOLVER:
  AMP:
    ENABLED: False
  OPT: Adam
  MAX_EPOCH: 120
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  BATCH_SIZE: 64

  SCHED: MultiStepLR
  STEPS: [ 40, 90 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 30
  BATCH_SIZE: 128

CUDNN_BENCHMARK: True

OUTPUT_DIR: ../runs/nsnet/
